config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task
  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel=“stylesheet” href=“https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css“>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

    <%= f.check_box :completed %>
    <%= f.label 'Completed:', class: 'form-control' %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit this task</h1>

<%= render 'form' %>

<div class="back-to-list">
  <%= link_to "Back to list", tasks_path %>
</div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
  <p><% @tasks.each do |task| %>
    <% if task.completed %>
      <div class="checkbox">
        <input type="checkbox" value="" checked>
        <span class="cr"><i class="cr-icon fa fa-check"></i></span>
        <%= link_to "#{task.title}", task_path(task.id) %>
        <%= link_to "Delete", destroy_task_path(task.id), method: 'delete', data: {confirm: "Are you sure?"} %>
      </div>
    <%else %>
      <div class="checkbox">
        <input type="checkbox" value="">
        <span class="cr"><i class="cr-icon fa fa-check"></i></span>
        <%= link_to "#{task.title}", task_path(task.id) %>
        <%= link_to "Delete", destroy_task_path(task.id), method: 'delete', data: {confirm: "Are you sure?"} %>
      </div>
    <% end %>
   <% end %>
   <div class="add-a-task">
    <p> <%= link_to "Add a task", new_task_path %></p>
   </div>
 </p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<!-- <div class="container">
  <form>
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div> -->

app/views/tasks/show.html.erb
<h1><%= @task[:title] %></h1>
<%= link_to "Edit this task", edit_task_path %>


<div class="task-description">
  <p><%= @task[:details] %></p>
</div>
<div class="task-status">
  <% if @task[:completed] == true %>
    <div class="checkbox">
      <p><input type="checkbox" value="" checked>
      <span class="cr"><i class="cr-icon fa fa-check"></i></span> This task is completed</p>
    </div>
  <%else %>
    <div class="checkbox">
      <p><input type="checkbox" value=""> This task is not completed !
      <span class="cr"><i class="cr-icon fa fa-check"></i></span></p>
    </div>
  <% end %>
</div>

<div class="back-to-list">
  <%= link_to "Back to list", tasks_path %>
</div>